# Generated by Django 5.1.5 on 2025-02-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
