# Generated by Django 5.1.5 on 2025-02-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0002_projects_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True, default='Access to this GitHub repository is currently unavailable.', null=True),
        ),
    ]
