# Generated by Django 5.1.2 on 2025-02-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0003_alter_projects_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
